name: t_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #util packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  connectivity_plus: ^6.1.4
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1
  modal_bottom_sheet: ^3.0.0
  shimmer: ^3.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product specific
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.1.1
  readmore: ^3.0.0

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # local assetsW
  assets:
    - assets/images/on_boarding_images/second.gif
    - assets/images/on_boarding_images/first.gif
    - assets/images/on_boarding_images/third.gif
    - assets/images/banners/banner_1.jpg
    - assets/logos/
    - assets/icons/
    - assets/images/

  # local fonts

