// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3mxrh3Shwh92NOovD9XBIJscoHZ4eVUo',
    appId: '1:63871893808:web:17508cb01c0787779308f5',
    messagingSenderId: '63871893808',
    projectId: 't-store-38e24',
    authDomain: 't-store-38e24.firebaseapp.com',
    storageBucket: 't-store-38e24.firebasestorage.app',
    measurementId: 'G-1ET6QGX1P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw9yXcRW7ykrHetjdbuUScgJQejUkLHiE',
    appId: '1:63871893808:android:f73a11e2ca74f0119308f5',
    messagingSenderId: '63871893808',
    projectId: 't-store-38e24',
    storageBucket: 't-store-38e24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPGsrSgzvUqBiZZu-UFsfG9eBUN6Q3-9o',
    appId: '1:63871893808:ios:48b3286136effc749308f5',
    messagingSenderId: '63871893808',
    projectId: 't-store-38e24',
    storageBucket: 't-store-38e24.firebasestorage.app',
    androidClientId: '63871893808-a67h8f4i3998aemc68dagnk8ifi47u4o.apps.googleusercontent.com',
    iosClientId: '63871893808-vpi0el60tfqru6deamlvsjfjbirsd3rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPGsrSgzvUqBiZZu-UFsfG9eBUN6Q3-9o',
    appId: '1:63871893808:ios:48b3286136effc749308f5',
    messagingSenderId: '63871893808',
    projectId: 't-store-38e24',
    storageBucket: 't-store-38e24.firebasestorage.app',
    androidClientId: '63871893808-a67h8f4i3998aemc68dagnk8ifi47u4o.apps.googleusercontent.com',
    iosClientId: '63871893808-vpi0el60tfqru6deamlvsjfjbirsd3rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3mxrh3Shwh92NOovD9XBIJscoHZ4eVUo',
    appId: '1:63871893808:web:c2401a2343aeb4aa9308f5',
    messagingSenderId: '63871893808',
    projectId: 't-store-38e24',
    authDomain: 't-store-38e24.firebaseapp.com',
    storageBucket: 't-store-38e24.firebasestorage.app',
    measurementId: 'G-Y4575TWV76',
  );

}